/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/Account.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    CommentForm: typeof import('./src/components/CommentForm.vue')['default']
    DisplayName: typeof import('./src/components/DisplayName.vue')['default']
    DisplayNameForm: typeof import('./src/components/DisplayNameForm.vue')['default']
    EmojiReaction: typeof import('./src/components/EmojiReaction.vue')['default']
    ExplanationText: typeof import('./src/components/ExplanationText.vue')['default']
    FeedbackPage: typeof import('./src/components/FeedbackPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MatomoOptOut: typeof import('./src/components/MatomoOptOut.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    PresentationEventsTimeline: typeof import('./src/components/PresentationEventsTimeline.vue')['default']
    PresentationFactsheet: typeof import('./src/components/PresentationFactsheet.vue')['default']
    PresentationListItem: typeof import('./src/components/PresentationListItem.vue')['default']
    ReactionsPanel: typeof import('./src/components/ReactionsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./src/components/SignIn.vue')['default']
    SignInMagicLink: typeof import('./src/components/SignInMagicLink.vue')['default']
    SignInUsernamePassword: typeof import('./src/components/SignInUsernamePassword.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    ThePresenterPage: typeof import('./src/components/ThePresenterPage.vue')['default']
  }
}
