#!/bin/sh

echo "🔍 Running pre-commit hook to check the code looks good... 🔍"

if ! npm run build; then
    echo "❌ Build failed! Please review TypeScript types."
    echo "Once you're done, don't forget to add your changes to the commit! 🚀"
    exit 1
fi

if ! npm run lint; then
    echo "❌ Linting failed!"
    echo "Once you're done, don't forget to add your beautification to the commit! 🤩"
    exit 1
fi

echo "👍 All good! Committing changes..."
