name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
    contents: read
    pages: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/deploy-prod')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install only prod. dependencies
      working-directory: ./packages/frontend
      run: npm ci --include=prod
    
    - name: Build for production
      working-directory: ./packages/frontend
      run: npm run build
      env:
        SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzdnlidWxxZGVtdGJ4bnp0c3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTY3OTgxMjgsImV4cCI6MjAzMjM3NDEyOH0.BKTRrISwv4NXGHc8OkpAmTFxlXChxVN9PrlTdKHrYaQ
        SUPABASE_API_URL: https://ksvybulqdemtbxnztsrw.supabase.co

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packages/frontend/dist