name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  # TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  HUSKY: 0

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --include=dev --include=prod

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Type Check
        run: npm run type-check

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

  verify-backend:
    runs-on: ubuntu-latest
    needs: build-lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        working-directory: ./packages/backend
        run: supabase start -x storage-api,imgproxy,inbucket,pgadmin-schema-diff,migra,postgres-meta,studio,edge-runtime,logflare,pg_prov,pgbouncer

      - name: Prepare env
        working-directory: ./packages/backend
        run: |
          supabase status -o yaml | while IFS=: read -r key value; do echo SUPABASE_"$key"=$(echo "$value" | sed 's/^ *//') >> $GITHUB_ENV; done

      - name: Verify generated types are checked in
        working-directory: ./packages/backend
        run: |
          supabase gen types typescript --local > types.gen.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
      - name: Execute API-tests
        working-directory: ./packages/backend
        run: |
          env
          npm ci --include=dev --include=prod
          npm t

  test-e2e:
    runs-on: ubuntu-latest
    needs: build-lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        working-directory: ./packages/backend
        run: supabase start -x storage-api,imgproxy,inbucket,pgadmin-schema-diff,migra,postgres-meta,studio,edge-runtime,logflare,pg_prov,pgbouncer

      - name: Prepare env
        working-directory: ./packages/backend
        run: |
          supabase status -o yaml | while IFS=: read -r key value; do echo SUPABASE_"$key"=$(echo "$value" | sed 's/^ *//') >> $GITHUB_ENV; done

      - name: Install dependencies
        working-directory: ./packages/frontend
        run: npm ci --include=dev --include=prod

      - name: Install Playwright
        working-directory: ./packages/frontend
        run: npx playwright install chromium --with-deps

      - name: Build again
        working-directory: ./packages/frontend
        run: npm run build

      - name: Execute end-to-end-tests
        working-directory: ./packages/frontend
        run: npm run test:e2e
        env:
          TEST_PRESENTER_EMAIL: test-presenter@local
          TEST_PRESENTER_PASSWORD: presenter
          TEST_AUDIENCE_EMAIL: test-audience@local
          TEST_AUDIENCE_PASSWORD: audience

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./packages/frontend/playwright-report/
          retention-days: 30