name: Continuous production test

on:
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent test
concurrency:
  group: 'prod-test'
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  prod-test:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install only dev dependencies
      working-directory: ./packages/frontend
      run: npm ci --include=dev

    - name: Install Playwright
      working-directory: ./packages/frontend
      run: npx playwright install chromium --with-deps


    - name: Execute end-to-end-tests on the production environment
      working-directory: ./packages/frontend
      run: npm run test:e2e
      env:
        BASE_URL: https://supaslides.dev
        TEST_PRESENTER_EMAIL: ${{ secrets.TEST_AUDIENCE_EMAIL }}
        TEST_PRESENTER_PASSWORD: ${{ secrets.TEST_PRESENTER_PASSWORD }}
        TEST_AUDIENCE_EMAIL: ${{ secrets.TEST_AUDIENCE_EMAIL }}
        TEST_AUDIENCE_PASSWORD: ${{ secrets. TEST_AUDIENCE_PASSWORD }}
        SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzdnlidWxxZGVtdGJ4bnp0c3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTY3OTgxMjgsImV4cCI6MjAzMjM3NDEyOH0.BKTRrISwv4NXGHc8OkpAmTFxlXChxVN9PrlTdKHrYaQ
        SUPABASE_API_URL: https://ksvybulqdemtbxnztsrw.supabase.co

    - name: Store test results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./packages/frontend/playwright-report/
        retention-days: 30
